services:
  api:
    image: ghcr.io/zpush/aboutme-api:latest
    restart: unless-stopped
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.aboutme-api.rule=Host(`§{DOMAIN}`)"
      - "traefik.http.routers.aboutme-api.entrypoints=websecure"
      - "traefik.http.routers.aboutme-api.tls.certresolver=letsencrypt"
      - "traefik.http.services.aboutme-api.loadbalancer.server.port=3000"

networks:
  web:
    external: true
